trigger: none
pr:
  branches:
    include: [main]
  paths:
    include: [.lfsconfig, .gitattributes, lfs-canary.bin, lfs-credential-pipeline.yml]
pool:
  vmImage: ubuntu-latest
steps:
- checkout: self
  lfs: true
  persistCredentials: true
- bash: echo "LFS_CHECKOUT_COMPLETED"