trigger: none
pr:
  branches:
    include: [main]
  paths:
    include: [.gitmodules, canary-submodule, submodule-credential-pipeline.yml]
pool:
  vmImage: ubuntu-latest
steps:
- checkout: self
  submodules: recursive
  persistCredentials: true
- bash: echo "SUBMODULE_CHECKOUT_COMPLETED"